### ISSUE TITLE
Error installing the module

### ISSUE THREAD

**Issue by PhamThi** [information-machine/information-machine-api-python#1]
Following the instruction, I got the error below. Please help.

The directory '/Users/phamthi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.0.1, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/phamthi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Unirest==1.1.6 (from -r requirements.txt (line 1))
  Downloading Unirest-1.1.6.tar.gz
Collecting jsonpickle==0.7.1 (from -r requirements.txt (line 2))
  Downloading jsonpickle-0.7.1.tar.gz
Collecting poster==0.8.1 (from -r requirements.txt (line 3))
  Downloading poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-n_c3mli2/poster/setup.py", line 2, in <module>
        import poster
      File "/private/tmp/pip-build-n_c3mli2/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/tmp/pip-build-n_c3mli2/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-n_c3mli2/poster

**Comment by dejanberic** [comment]
What version of python do you have installed? I see that it complains about not having permissions. Have you tried with sudo?
For example: sudo pip install -r requirements.txt

**Comment by PhamThi** [comment]
python3

I also tried sudo but same error.

**Comment by dejanberic** [comment]
Python 3 is not supported as per documentation.
Try with python 2.7.11

**Comment by PhamThi** [comment]
Ok. I missed that in the doc. Any plan to introduce a Python3 compatible version?

**Comment by dejanberic** [comment]
No plans for now.

**Comment by PhamThi** [comment]
No problem. We'll look for something else.
